stages:
  - test

services: []

before_script:
  - pip install -r requirements.txt

test_python:3.4:
  stage: test
  image: python:3.4
  script:
    - ./test.sh

test_python:3.5:
  stage: test
  image: python:3.5
  script:
    - ./test.sh
